# Generated by Django 2.2 on 2019-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActuacionParlamentaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legislador', models.IntegerField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actuacion_parlamentaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenciaComisiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comision', models.IntegerField(blank=True, null=True)),
                ('id_legislador', models.IntegerField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('citaciones', models.IntegerField(blank=True, null=True)),
                ('asistencias', models.IntegerField(blank=True, null=True)),
                ('faltas_con_aviso', models.IntegerField(blank=True, null=True)),
                ('faltas_sin_aviso', models.IntegerField(blank=True, null=True)),
                ('licencia', models.IntegerField(blank=True, null=True)),
                ('otras_comisiones', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia_comisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenciaPlenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legislador', models.IntegerField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('citaciones', models.IntegerField(blank=True, null=True)),
                ('asistencias', models.IntegerField(blank=True, null=True)),
                ('faltas_con_aviso', models.IntegerField(blank=True, null=True)),
                ('faltas_sin_aviso', models.IntegerField(blank=True, null=True)),
                ('licencia', models.IntegerField(blank=True, null=True)),
                ('pasaje_presidencia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia_plenario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comisiones',
            fields=[
                ('id_comision', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_legislador', models.IntegerField(blank=True, null=True)),
                ('fecha_ini', models.TextField(blank=True, null=True)),
                ('camara', models.TextField(blank=True, null=True)),
                ('lema', models.TextField(blank=True, null=True)),
                ('departamento', models.TextField(blank=True, null=True)),
                ('sublema', models.TextField(blank=True, null=True)),
                ('fecha_fin', models.TextField(blank=True, null=True)),
                ('titular', models.TextField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'convocatoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvolucionProyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.IntegerField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('id_comision', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evolucion_proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Legisladores',
            fields=[
                ('id_legislador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('lema', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'legisladores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidosInforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.IntegerField(blank=True, null=True)),
                ('id_legislador', models.IntegerField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('organismo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidos_informe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('presentado_por', models.TextField(blank=True, null=True)),
                ('evolucion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectosPresentados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.IntegerField(blank=True, null=True)),
                ('id_legislador', models.IntegerField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyectos_presentados',
                'managed': False,
            },
        ),
    ]
